### ISSUE TITLE
Petite Modification dand si4684.cpp et .h

### ISSUE THREAD

**Issue by GOUNOT** [PE5PVB/SI4684-DAB-Receiver#5]
Bonjour ,

Voici les fichier si4684.cpp et . h
Ajout radio.vol(x); Volume de sortie
SID et EID recalculés

Pascal
[si4684h.txt](https://github.com/PE5PVB/SI4684-DAB-Receiver/files/15418648/si4684h.txt)
[si4684cpp.txt](https://github.com/PE5PVB/SI4684-DAB-Receiver/files/15418651/si4684cpp.txt)

**Comment by PE5PVB** [comment]
Hi Pascal,

 

Thanks. I applied your changes to the repository.

Maybe you can help me out with translation of the language.h to French?

 

BTW. Do you have EPG data on your DAB bouquets? We don’t, and I like to parse now/next EPG for the current service and show it in a separate window when long press the slideshow button.

 

Sjef

 

Van: GOUNOT ***@***.***> 
Verzonden: donderdag 23 mei 2024 16:57
Aan: PE5PVB/SI4684-DAB-Receiver ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [PE5PVB/SI4684-DAB-Receiver] Petite Modification dand si4684.cpp et .h (Issue #5)

 

Bonjour ,

Voici les fichier si4684.cpp et . h
Ajout radio.vol(x); Volume de sortie
SID et EID recalculés

Pascal
si4684h.txt <https://github.com/PE5PVB/SI4684-DAB-Receiver/files/15418648/si4684h.txt> 
si4684cpp.txt <https://github.com/PE5PVB/SI4684-DAB-Receiver/files/15418651/si4684cpp.txt>

**Comment by PE5PVB** [comment]
I tried your modification but it mess up German.
![image](https://github.com/PE5PVB/SI4684-DAB-Receiver/assets/76666293/459cc50f-783b-4a7c-8554-0ab3782b69b5)
