### ISSUE TITLE
Language en ftançais

### ISSUE THREAD

**Issue by GOUNOT** [PE5PVB/SI4684-DAB-Receiver#6]
Hello, 
As requested, here is the language in French.
 
Cordialement Pascal
[language.h.txt](https://github.com/PE5PVB/SI4684-DAB-Receiver/files/15433782/language.h.txt)

**Comment by PE5PVB** [comment]
Thanks.

 

I commited it to Github.

 

I think you are not using my latest commit. I translated "Waiting for list", // 73 to "Attente liste", // 73

Hopefully, that’s correct French 😉

 

Sjef

 

Van: GOUNOT ***@***.***> 
Verzonden: vrijdag 24 mei 2024 13:54
Aan: PE5PVB/SI4684-DAB-Receiver ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [PE5PVB/SI4684-DAB-Receiver] Language en ftançais (Issue #6)

 

Hello,
As requested, here is the language in French.

Cordialement Pascal
language.h.txt <https://github.com/PE5PVB/SI4684-DAB-Receiver/files/15433782/language.h.txt>

**Comment by PE5PVB** [comment]
Done
